name: Build Debian Package

on:
  push:
    tags:
      - '*'
    branches:
      - main

jobs:
  build-package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "Molham Al Nasr"
          git config --global user.email "dr.molham93@gmail.com"

      - name: Determine version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Clone repository to package directory
        run: |
          mkdir "x735-script-${VERSION}"
          cp -a . "x735-script-${VERSION}"

      - name: Set version in DEBIAN/control file
        run: |
          sed -i "s/^Version:.*$/Version: ${VERSION}/" "x735-script-${VERSION}/DEBIAN/control"

      - name: Install dpkg and dependencies
        run: sudo apt-get -y install dpkg-dev

      - name: Build Debian package
        run: sudo dpkg-deb --build "x735-script-${VERSION}"

      - name: Archive Debian package
        run: mv "x735-script-${VERSION}.deb" "x735-script-${VERSION}.deb"

      - name: Save Debian package as artifacts
        uses: actions/upload-artifact@v2
        with:
          name: x735-script-${VERSION}.deb
          path: x735-script-${VERSION}.deb
